### ISSUE TITLE
New User - Basic Questions from Companion

### ISSUE THREAD

**Issue by muzicman82** [JeffreyDavidsz/VICRO-Listener-ISSUES#12]
Hi all,

I'm up and connected with Companion Pi, connecting to a Windows 11 PC. Here's some basic questions I have...

- I see from the list of actions which ones are Pro actions. Is this documented anywhere else?
- I don't see any feedbacks listed. Is there a way I can get the mute/unmute status so that I can update the button to accurately show whether a system is muted or unmuted? Another feedback function would be to show the current volume level.

**Comment by JeffreyDavidsz** [comment]
Hi, Should be documenten in the help file, but to be honest might not be updated at all. There is no feedback other than mouse coordinates (when you send a subscribe command first). 
The feedback you request is a OS specific thing and not really the purpose for the listener. If you want I can take a look is this is possible and create an other program for that

**Comment by muzicman82** [comment]
That would be great... Should this be added, I'll gladly subscribe to PRO. For me, true feedback is important.
