### ISSUE TITLE
'Up' and 'Down' keys stick down

### ISSUE THREAD

**Issue by Ajonymous** [JeffreyDavidsz/VICRO-Listener-ISSUES#14]
Hi,

I have only recently had this issue. When I use the key press down and up actions, when I have pressed they key, it sticks down even after releasing the key with the up action. 

The vicreo app shows the up command has been sent but still the key remains down.

I've tried version 6, 8 and 8.1.4
In version 6 it works but others do not.  I dont have the downloads for other versions
Running W11

Thanks

**Comment by JeffreyDavidsz** [comment]
Did you try to put a bit delay in between the commands? And what do you use in between. Can you do a screenshot of your actions and of the log?

**Comment by Ajonymous** [comment]
Yeah tried a delay of 0 and 100 no luck.

This is on V8.1.4

Log records:
16:36:18 received: {"key":"F13","type":"up","password":"ffdd744ab4930c1853a6fbebbe8516aa"}
16:36:15 received: {"key":"F13","type":"down","password":"ffdd744ab4930c1853a6fbebbe8516aa"}

Action
![image](https://github.com/JeffreyDavidsz/VICREO-Listener-ISSUES/assets/51542347/fd9ba86f-0d85-48e9-8373-5abb0d87b30c)

Swapped out to V6.0.0 and worked straight away

**Comment by JeffreyDavidsz** [comment]
I've finally found the issue its now fixed in 8.1.7 it will be uploaded today (if the build goes ok). You know with the special key you can do the F13 also right? But you probably need it this way.
