### ISSUE TITLE
Vicreo Hotkey send shell command seems not to work properly

### ISSUE THREAD

**Issue by jordinordbeck** [JeffreyDavidsz/VICRO-Listener-ISSUES#3]
I want to overwrite a file using Vicreo Hotkey module with Companion. Vicreolistener is connected at the same computer 
The proper syntax with CMD is:
copy /-y C:\Users\Globalroom\Documents\LLISTA_ALUMNES.xlsx  C:\Users\Globalroom\Desktop\LLISTA_ALUMNES.xlsx

(/-y is an optional parameter)
I'm trying to write the proper syntax in the "VicreoHotKey Send shell command" action according the guide found in https://www.vicreo-listener.com/ but nothing happens. The VicreoListener logs window does not prompt for any message received. Other Vicreo actions like send a key work fine.

**Comment by JeffreyDavidsz** [comment]
/ is a bit tricky it can escape code so it's filtered. What is de exact command you use and did you try a simple command to check if everything is working? Also versions are important to know

**Comment by jordinordbeck** [comment]
A simple dir  command (without "") prompts the directory list into the Vicreo Listener logs window.
A simple copy command (without arguments) is received but an error is prompted because improper sintax
But copy command with arguments does not prompts any result in the logs windows. I've tried with and without "". For example:
"copy", "C:\Users\Globalroom\Documents\LLISTA_ALUMNES.xlsx" "C:\Users\Globalroom\Desktop\LLISTA_ALUMNES.xlsx"
I use Bitfocus Companion version 2.2.0-487e2889-3684 and Vicreo Listener version 3.0.3 with the password field empty. I assume that I need to configure VicreoHotkey with Version > 3.0.0. setting.

**Comment by JeffreyDavidsz** [comment]
I did a fix for this. It;s in the latest Companion beta and also with version 4.0.11 of the listener. Did a copy "soucre" "distination"
