### ISSUE TITLE
Hotkeys doing nothing

### ISSUE THREAD

**Issue by BrianBATL** [JeffreyDavidsz/VICRO-Listener-ISSUES#5]
Not sure what I'm doing wrong.  Had Vicreo hotkeys working before the "password" update, and have since taken quite a few months off of shooting videos due to health issues, but am back at it again and I can't get any vicreo hotkey buttons/code in campanion to work.

In companion, the "status" is green and ok (connected to vicreo listener).  It's connecting to the IP and port just fine.  When I hit hotkeys on my stream deck, it sends commands to the vicreo log box.

![v1a](https://user-images.githubusercontent.com/87454026/158099356-d972996e-73a6-4fbc-be82-53670638a756.jpg)

But any button I setup isn't working.  It transmits the attempted execution of the button to the vicreo listener log box with some odd thing that says, "When you want to use modifiers, use the combination or trio syntax please", and then the next line is the button i'm trying to execute, which doesn't ever execute.

It could be something as simple as trying to do a single function like pressing "f" to go fullscreen, or a combination function like "command+shift+right" which is trying to snap the active screen to the right adjacent monitor, but nothing works anymore.

What am I missing?

**Comment by JeffreyDavidsz** [comment]
Did you change the version in companion?

**Comment by BrianBATL** [comment]
Yes. It is on Version > 2.0.5.  And still doing the same thing.

For some strange reason, it appears to be trying to send modifiers every time, when there aren't any.

Even on a "Hot (single) key", it's sending { "key" : "f", "type" : "press", "modifiers" : [ ] }
And then we see the line, "When you want to use modifiers, use the combination or trio syntax please".

Suggesting that the function is sending modifiers and therefore the "single key" is the wrong function format.  But it's not.  I'm literally just asking for a single action.  As you can see below, I've made the button as simple as possible.  A single hotkey that presses "f", and yet the Vicreo log box says I'm trying to send "modifiers", when it's not. And this is why I think it's failing to execute the button.

![v2a](https://user-images.githubusercontent.com/87454026/158172679-bc42c389-3d2f-4441-99f1-9395b6e66d99.jpg)

![v1b](https://user-images.githubusercontent.com/87454026/158172722-286ce7aa-a2b2-4008-8d4f-1da6bfbeb690.jpg)


BUT, it's doing this with every vicreo hotkey button I've made, even the combination and trio ones as seen below.  You can clearly see it's a trio function, and it's STILL giving the error message that I need to use combination and trio syntax when using modifiers.

![v2b](https://user-images.githubusercontent.com/87454026/158174378-cad388a6-01d9-49e5-b650-987fd87d9361.jpg)

![v1c](https://user-images.githubusercontent.com/87454026/158174409-a6316cef-036c-4c38-9e4d-04840be31b61.jpg)

**Comment by JeffreyDavidsz** [comment]
You are on version > 3.0.0 but if you cannot select that. You need a newer version of Companion. A Beta or Release candidate

**Comment by BrianBATL** [comment]
Ok so I installed the companion version that allows you > 3.0.0 to work and set the target IP to 127.0.0.1 and this finally got it to where some buttons worked.  Anything that's a single hotkey or key press works fine.  Even your preset that does ctrl+alt+tab (trio example) works.

HOWEVER, anything with a special key doesn't work.  If I try a trio key of command+shift+arrow left, nothing happens.  It sends the function to the vicreo log box and even says "received", but it doesn't snap the active window left.

And, your preset combination example (alt+tab) doesn't work properly.  I see the active windows very briefly flash on the screen for like a nanosecond on pressing it, but it doesn't cycle through the windows.

Any ideas?
