### ISSUE TITLE
Macbook receives, but doesn't process commands

### ISSUE THREAD

**Issue by video84005** [JeffreyDavidsz/VICRO-Listener-ISSUES#7]
Macbook pro, OS 10.15.7
Vicreo Listener 5.0.0 Basic, no license
PowerPoint 15.29
Companion 2.2.0 (3998-ccea40c7), Windows 10

Vicreo receives commands but won't process them.  Specifically looking to advance PowerPoint, but I have also tried "Cmd-F" to open Finder window, no action. 3 other Macbooks with identical setups functioning without issue.

**Comment by JeffreyDavidsz** [comment]
Did you do all settings as shown on the www.vicreo-listener.com/faq ? Tried a reboot after that? Try to make a screen shot of the log so I can see which command is being send (new version of companion released yesterday, which also has updates for vicreo-listener

**Comment by video84005** [comment]
All Accessibility settings enabled. many reboots. just updated to 2.2.1 (4443-v2-2.1-98594c92) - same issue.

screenshot doesn't show full log, but trying commands: Start from Top, Next, Previous.

<img width="478" alt="Screen Shot 2022-05-31 at 4 10 47 PM" src="https://user-images.githubusercontent.com/106626250/171277742-dfa531ad-79b5-4781-9cf1-12464c8404e4.png">

**Comment by JeffreyDavidsz** [comment]
All right seems something with osx indeed. Might be able to clear the access and reapply it (might be better to remove the access, so osx will ask you again)

**Comment by video84005** [comment]
Clearing access and rebooting seems to have solved the issue.  Thank you.

**Comment by JeffreyDavidsz** [comment]
Great have fun
